use std::{env, path::Path, process::Command};

// Cargo only re-runs a build script when one of its declared inputs changes. Git's HEAD/index
// cover commits and staged edits, but not an unstaged edit to a file that Tauri embeds. Keep this
// list aligned with tauri.conf.json plus the desktop crate inputs so cached provenance can never
// survive a change to bytes that may ship in the app.
const SHIPPED_INPUTS: &[&str] = &[
    "../frontend",
    // The staged copy Tauri actually embeds (build.frontendDist): frontend/ minus the industrial
    // review/source art, regenerated by scripts/stage-frontend-dist.mjs before every desktop build.
    // Gitignored like binaries/ and voice-deps/, but it DOES ship, so a stale stage must rerun us.
    "frontend-dist",
    "../sidecar",
    "../shared",
    "src",
    "capabilities",
    "icons",
    "installer",
    "binaries",
    // Staged runtime node_modules for the offline voice engine. Gitignored and generated by
    // scripts/stage-voice-deps.mjs, so — like binaries/ — it never makes a normal build dirty, but it
    // DOES ship, and a cached build that missed a re-stage would package a stale engine.
    "voice-deps/node_modules",
    "build.rs",
    "Cargo.toml",
    "Cargo.lock",
    "tauri.conf.json",
];

// git describe --dirty intentionally ignores untracked files. These are the repository-relative
// roots whose Git-owned contents are packaged; include untracked additions when deciding whether
// the source identity is dirty. Gitignored generated inputs (notably binaries/) remain governed by
// the artifact hash rather than making every normal release build dirty.
const SHIPPED_GIT_ROOTS: &[&str] = &["frontend", "sidecar", "shared", "src-tauri"];

/// P1.5 (UPDATE_STATE_SAFETY_AUDIT): embed the git commit + dirty state at COMPILE TIME so every binary can say
/// exactly which source it was built from. `git describe --always --dirty` yields e.g. `c160d905` (clean) or
/// `c160d905-dirty` (uncommitted working tree — the exact hazard the audit flagged: locally-built installers with
/// bumped-then-reverted versions and no tag). Git missing / not a repo → "unknown" (never fail the build).
///
/// The values are exposed to the Rust code as compile-time env via `env!("STARNET_BUILD_COMMIT")` etc. They land in
/// the binary's read-only string data (survives `strip = true`, which only drops debug symbols) so the release
/// train can grep the built exe for the expected commit.
fn git_output(args: &[&str]) -> Option<String> {
    let out = Command::new("git").args(args).output().ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() {
        None
    } else {
        Some(s)
    }
}

fn shipped_inputs_dirty() -> Option<bool> {
    // Tauri can rewrite Cargo.toml with host-native CRLF while preserving identical
    // content (the release train verifies and restores that artifact after build).
    // A porcelain status check sees the rewrite before Rust compilation and would
    // permanently stamp an otherwise reproducible binary as dirty-dev. Compare all
    // tracked shipped inputs to HEAD while ignoring CR-at-EOL only, then check
    // untracked shipped inputs separately so genuinely new packaged files still
    // fail closed.
    let mut diff = Command::new("git");
    diff.args([
        "-C",
        "..",
        "diff",
        "--quiet",
        "--ignore-cr-at-eol",
        "HEAD",
        "--",
    ]);
    diff.args(SHIPPED_GIT_ROOTS);
    let status = diff.status().ok()?;
    match status.code() {
        Some(0) => {}
        Some(1) => return Some(true),
        _ => return None,
    }

    let mut untracked = Command::new("git");
    untracked.args([
        "-C",
        "..",
        "ls-files",
        "--others",
        "--exclude-standard",
        "--",
    ]);
    untracked.args(SHIPPED_GIT_ROOTS);
    let out = untracked.output().ok()?;
    if !out.status.success() {
        return None;
    }
    Some(!out.stdout.is_empty())
}

fn emit_git_rerun_path(name: &str) {
    if let Some(path) = git_output(&["rev-parse", "--git-path", name]) {
        if Path::new(&path).exists() {
            println!("cargo:rerun-if-changed={path}");
        }
    }
}

fn emit_rerun_inputs() {
    println!("cargo:rerun-if-env-changed=STARNET_BUILD_PROVENANCE_KIND");
    for path in SHIPPED_INPUTS {
        println!("cargo:rerun-if-changed={path}");
    }

    // Resolve Git's real files instead of assuming ../.git is a directory. In a worktree it is a
    // text file, while HEAD/index and the branch ref live under the integration tree's .git area.
    for name in ["HEAD", "index", "packed-refs"] {
        emit_git_rerun_path(name);
    }
    if let Some(head_ref) = git_output(&["symbolic-ref", "-q", "HEAD"]) {
        emit_git_rerun_path(&head_ref);
    }
}

fn exact_git_oid(value: &str) -> bool {
    value.len() == 40 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

// BuildInfo may report the open-source build's base class, but a build environment can never
// self-assert `official`. That label is promoted later by installed proof only after external
// release evidence matches this commit, tree, and the running executable bytes.
fn build_provenance_kind(dirty: bool, commit: &str, source_tree: &str) -> &'static str {
    if dirty || !exact_git_oid(commit) || !exact_git_oid(source_tree) {
        return "dirty-dev";
    }
    match env::var("STARNET_BUILD_PROVENANCE_KIND")
        .unwrap_or_default()
        .trim()
        .to_ascii_lowercase()
        .as_str()
    {
        "" | "reproducible-source" => "reproducible-source",
        "custom" => "custom",
        // `official` and every unknown declaration are custom until external evidence earns
        // another classification. This prevents a one-line environment assertion from forging
        // the official label while preserving owner/source-builder authority.
        _ => "custom",
    }
}

fn main() {
    emit_rerun_inputs();

    // `--always` falls back to the short hash when there is no tag; `--dirty` appends `-dirty` on an unclean tree.
    let mut describe = git_output(&["describe", "--always", "--dirty", "--tags"])
        .unwrap_or_else(|| "unknown".to_string());

    // `git describe --dirty` sees every repository edit, including operational QA receipts that are
    // deliberately outside the packaged app. The shipped-root status is the authoritative product
    // dirt signal and also catches untracked packaged inputs. Fall back to describe only when Git
    // cannot answer the scoped status query, so provenance remains fail-closed.
    let describe_dirty = describe.ends_with("-dirty");
    let dirty = shipped_inputs_dirty().unwrap_or(describe_dirty);
    if dirty && !describe_dirty && describe != "unknown" {
        describe.push_str("-dirty");
    } else if !dirty && describe_dirty {
        describe.truncate(describe.len() - "-dirty".len());
    }
    let commit =
        git_output(&["rev-parse", "--short", "HEAD"]).unwrap_or_else(|| "unknown".to_string());
    // The short value remains the human-facing diagnostic label. The full SHA is a separate release-proof
    // identity: prefix matching is not strong enough to bind an installed artifact to one immutable candidate.
    let full_sha = git_output(&["rev-parse", "HEAD"]).unwrap_or_else(|| "unknown".to_string());
    let source_tree =
        git_output(&["rev-parse", "HEAD^{tree}"]).unwrap_or_else(|| "unknown".to_string());
    let provenance_kind = build_provenance_kind(dirty, &full_sha, &source_tree);

    println!("cargo:rustc-env=STARNET_BUILD_COMMIT={}", commit);
    println!("cargo:rustc-env=STARNET_BUILD_SHA={}", full_sha);
    println!("cargo:rustc-env=STARNET_BUILD_TREE={}", source_tree);
    println!(
        "cargo:rustc-env=STARNET_BUILD_PROVENANCE_KIND={}",
        provenance_kind
    );
    println!("cargo:rustc-env=STARNET_BUILD_DESCRIBE={}", describe);
    println!(
        "cargo:rustc-env=STARNET_BUILD_DIRTY={}",
        if dirty { "1" } else { "0" }
    );

    tauri_build::build();
}
