'use strict';
const assert = require('node:assert/strict');
const { makeNotebookTools } = require('../sidecar/tools/builtin/notebook.js');
const { reflect } = require('../sidecar/reflect.js');
const { rank, renderRecall, compactionMemoryBlock } = require('../sidecar/context.js');
const { appendPending, listPending } = require('../sidecar/memory-store.js');

(async () => {
  let records = [], now = 1000, fail = false;
  const store = { get: () => records, async update(_key, fn) {
    const next = fn(records);
    if (fail) throw Error('disk unavailable');
    if (next !== undefined) records = next;
  } };
  const tools = makeNotebookTools({ store, clock: { now: () => ++now } });
  const ctx = { agentId: 'agent', streamId: 'acme', runId: 'first' };
  const old = 'User prefers rounded purple cards for Acme website design';
  const revised = 'User does not prefer rounded purple cards for Acme website design';
  const blue = 'User prefers square blue cards for Acme website design; reference approved/acme.png';
  await tools.writeTool.run({ title: 'Acme design', body: old, pinned: true }, ctx);
  const challenged = await tools.writeTool.run({ title: 'Acme design', body: revised }, ctx);
  assert.match(challenged.content, /replaceId/);
  assert.equal(records.length, 1);
  const updated = await tools.writeTool.run({ title: 'Acme design', body: revised, replaceId: 'note_1', previousBody: old }, {...ctx, runId:'correction'});
  assert.match(updated.content, /^Updated note/);
  assert.equal(records.length, 1);
  assert.equal(records[0].body, revised);
  assert.equal(records[0].content, revised);
  assert.equal(records[0].id, 'note_1');
  assert.equal(records[0].history[0].body, old);
  assert.equal(records[0].sourceRunId, 'first');
  assert.equal(records[0].updatedSourceRunId, 'correction');
  assert.equal(records[0].pinned, true);
  assert.equal(records[0].scope, 'stream');
  assert.equal(records[0].streamId, 'acme');
  const newlyCorrected={...records[0],pinned:false,createdAt:1,updatedAt:now};
  assert.equal(rank([{id:'other',body:revised,createdAt:now-100},newlyCorrected],revised,{now,k:1})[0].id,'note_1','a correction is ranked at its update time, not its original age');
  assert.match(renderRecall(rank(records, 'Make another one', {now,streamId:'acme'})).text, /does not prefer/);
  assert.equal(rank(records, 'Make another one', {now,streamId:'other'}).length, 0);
  assert.match(compactionMemoryBlock(records, 'Continue', {now,streamId:'acme'}), /does not prefer/);
  assert.doesNotMatch(renderRecall(rank(records, 'Acme', {now,streamId:'acme'})).text, /• .*User prefers rounded/);
  await assert.rejects(tools.writeTool.run({title:'Acme design',body:blue,replaceId:'note_1',previousBody:old},ctx), /changed since/);
  assert.equal(records[0].body, revised);
  fail = true;
  await assert.rejects(tools.writeTool.run({title:'Acme design',body:blue,replaceId:'note_1',previousBody:revised},ctx), /disk unavailable/);
  fail = false;
  assert.equal(records[0].body, revised);
  await assert.rejects(tools.writeTool.run({title:'Acme design',body:blue,replaceId:'note_9',previousBody:revised},ctx), /no such memory/);
  const run = {runId:'reflect',messages:[{role:'user',content:blue}]};
  const proposal = await reflect(run, {existing:records,propose:async()=> 'UPDATE note_1: '+blue});
  assert.equal(proposal.proposals[0].replaceId, 'note_1');
  assert.equal(proposal.proposals[0].previousBody, revised);
  assert.equal(proposal.proposals[0].scope, 'stream');
  assert.equal(proposal.proposals[0].streamId, 'acme');
  assert.match(proposal.prompt, /UPDATE note_ID/);
  const inverted = await reflect(run, {existing:[{id:'note_1',body:old}],propose:async()=> 'PREFERENCE: '+revised});
  assert.equal(inverted.proposals[0].replaceId, 'note_1', 'an opposite preference reaches review, never silent dedup');
  const unknown = await reflect(run, {existing:records,propose:async()=> 'UPDATE note_9: '+blue});
  assert.equal(unknown.proposals.length, 0);
  const resurrected = await reflect(run, {existing:records,propose:async()=> 'PREFERENCE: '+old});
  assert.equal(resurrected.proposals.length, 0, 'ordinary reflection cannot resurrect archived text');
  let pending = [];
  const pendingStore = {get:()=>pending,update:async(_key,fn)=>{pending=fn(pending)||pending;}};
  await appendPending(pendingStore,'agent','reflect',proposal.proposals,now);
  pending = JSON.parse(JSON.stringify(pending));
  assert.equal(listPending(pendingStore,'agent')[0].previousBody, revised);
  assert.equal(listPending(pendingStore,'agent')[0].replaceId, 'note_1');
  await tools.writeTool.run({title:'Reply preference',body:'User prefers concise responses',scope:'global',pinned:true,distinct:true},ctx);
  assert.equal(records[1].streamId, null);
  assert.match(renderRecall(rank(records,'Continue',{now,streamId:'other'})).text,/concise/);
  assert.doesNotMatch(renderRecall(rank(records,'Continue',{now,streamId:'other'})).text,/Acme/);
  const projectNote={...records[0],projectRoot:'C:\\Work\\Acme'};
  assert.equal(rank([projectNote],'Make another one',{now,streamId:'new-project-session',projectRoot:'c:/work/acme/'}).length,1);
  assert.equal(rank([projectNote],'Make another one',{now,streamId:'new-project-session',projectRoot:'C:/Work/Other'}).length,0);
  assert.equal(rank([projectNote],'Make another one',{now,streamId:'new-project-session'}).length,0);
  assert.equal(rank([projectNote],'Acme website design',{now,streamId:'new-project-session',projectRoot:'C:/Work/Other'}).length,0);
  assert.equal(rank([projectNote],'Acme website design',{now,streamId:'new-project-session',floor:false}).length,1);
  console.log('memory-corrections.test: PASS (corrections, stale writes, failed persistence, review, scope, compaction)');
})().catch(e=>{console.error(e);process.exitCode=1;});
