'use strict';
const assert=require('node:assert/strict');
global.IndustrialTextures={enabled:()=>true,isRemaster:()=>true,ready:Promise.resolve()};
const P=require('../frontend/app/propsprites.js'),{polishStation,validatePolish}=require('../dev/polish-prop-layout.cjs');
const before=require('./fixtures/prop-layout-geometry.json'),original=JSON.stringify(before);
const {station}=polishStation(before,id=>P.spec(id));
const check=s=>validatePolish(before,s,id=>P.spec(id),(id,r)=>P.viewAt(id,r));
assert.equal(JSON.stringify(before),original,'source layout remains untouched');
assert.deepEqual(check(station).errors,[]);
assert.equal(station.props.filter(p=>p.t==='desk2'&&p.w===3).length,3);
assert.deepEqual(station.props.filter(p=>p.t==='desk'),before.props.filter(p=>p.t==='desk'),'accepted compact workstations preserved');
assert.equal(station.props.find(p=>p.id==='p68').r,0);
const wrong=structuredClone(station);wrong.props.find(p=>p.id==='p68').r=2;
assert.ok(check(wrong).errors.some(e=>e.includes('unsupported direction')));
const collision=structuredClone(station);Object.assign(collision.props.find(p=>p.id==='polish-archive-books'),{x:-1,y:-27});
assert.ok(check(collision).errors.some(e=>e.includes('overlapping')));
const unsupported=structuredClone(station);unsupported.props.find(p=>p.id==='polish-support-table').t='industrial_drawerbank';
assert.ok(check(unsupported).errors.some(e=>e.includes('missing table support')));
const closed=structuredClone(station);closed.props.push({id:'blocked-door',t:'industrial_locker',x:2,y:-20,w:2,h:1});
assert.ok(check(closed).errors.some(e=>e.includes('Lost circulation')));
console.log('PASS: 159 placements, supported directions, proper desk2 footprints, preserved anchors, surface support and circulation; invalid layouts rejected.');
