import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import {slugify,fingerprintFor} from '../../scripts/qa/bugs.mjs';
const rows=[
 ['A1','Startup history read failure skips away-work review recovery','sessions','P1','frontend/app/returnstore.js:78','away-read-failure-loses-recovery-boundary','A failed first history read leaves a completed away run absent from the pending review list even after the next successful boot.','Seed lastSeenAt=1000 and a done run at 2000. Boot at 3000 with a rejected history read, then at 4000 with that run returned. Both pending lists stay empty.'],
 ['A2','Agent loop pause leaves cancelled iteration running and lease held','autonomy','P1','sidecar/index.js:7315','loop-agent-pause','Agent-command pause can show the loop paused while its iteration remains running and prevents ordinary progress.','Start a loop with an unresolved provider promise; call actual modelControlLoop pause; resolve the provider after abort. The iteration remains running and leases.size is 1. Reference abortLease settles cancelled and releases ownership.'],
 ['A3','Routine follow-up checkbox saves an unusable session origin','autonomy','P1','frontend/app/windows/routines.js:653','routine-follow-up-without-origin','A saved routine with follow-up enabled is rejected by the scheduler because it has no captured conversation.','In New schedule leave Keep in StarNet selected, check Allow follow-up, fill name and prompt, save. Inspect job: attachToSession true, origin null. Actual cronPreflightConfig returns missing-session-origin. This persisted through an isolated sidecar restart.'],
 ['A4','Routine form provider overrides its selected agent provider','providers','P1','frontend/app/windows/routines.js:622','routine-station-provider-overrides-selected-agent','A routine assigned to one provider-configured agent can retain the global station provider instead, producing a mixed execution configuration.','Give a selected agent provider codex while the form station provider is openrouter. The UI sends the station value as job.provider; actual cronProviderFor resolves openrouter instead of codex. Paid dispatch remains unverified.'],
 ['A5','Loop polling erases the rejection explanation being typed','autonomy','P2','frontend/app/windows/loops.js:303','loop-review-draft-reset','A typed rejection explanation vanishes and its editor closes while the user is composing it.','Run the local fault proxy, open Automation Goal loops, click REJECT on the candidate, type a reason, and let the four-second refresh run. UI reads change from the typed text with hidden false to empty with hidden true.'],
 ['A6','Loop pause and resume discard refused control responses','autonomy','P2','frontend/app/windows/loops.js:381','loop-pause-error-hidden','A failed Pause request offers no error or retry feedback, leaving the user to infer whether the loop stopped.','Run the fault proxy and click loop PAUSE. It records the request and returns HTTP 409 with a review-busy error. UI retains loops running and Pause, with no notification.'],
 ['A7','Outbox run review can display another run answer','sessions','P2','frontend/app/windows/outbox.js:127','outbox-output-attributed-to-wrong-run','A review crate can pair its original request and rating target with a later answer from the same session.','Execute the unchanged rendering block with crate runId A and a transcript containing request/answer A followed by request/answer B. It displays request A and answer B. This is a source reproduction, not a paid live transcript.'],
 ['A8','Local settings save failure still permits saved confirmation','world','P2','frontend/app/stationui.js:180','settings-save-failure-swallowed','Local preference controls can report saved after storage rejected the write; the in-memory setting can revert on reload.','Execute actual stationui save with localStorage.setItem throwing. It returns without an error; appearance and notification callers unconditionally flashSaved. Actual disk-full UI was not tested.'],
 ['A9','Shared query refresh cannot retire a stalled predecessor','sessions','P2','frontend/app/queryspine.js:91','query-refresh-waits-on-hung-predecessor','Retry can remain pending behind an old unfinished JSON request instead of making a fresh request.','Start QuerySpine cron refresh with an unsettled transport; invalidate and refresh again. Wire calls stay at 1 and pending stays true. Harness.api.get has no application deadline.']
];
const map=[];
for(const [id,title,surface,severity,anchor,receipt,symptom,repro] of rows){
 const slug=slugify(title),fp=fingerprintFor({surface,slug});
 const file=`qa/bugs/${fp}-${slug}.md`;
 if(!fs.existsSync(file)){
  const r=spawnSync(process.execPath,['scripts/qa/bugs.mjs','--new','--title',title,'--surface',surface,'--severity',severity,'--lane','agent/seam-audit-0912-b','--origin','audit'],{encoding:'utf8'});
  if(r.status!==0)throw Error(r.stdout+r.stderr);
 }
 if(!fs.readFileSync(file,'utf8').includes('lane: agent/seam-audit-0912-b'))throw Error('Refusing another lane record '+file);
 const text=`---\nfingerprint: ${fp}\nslug: ${slug}\ntitle: ${title}\nsurface: ${surface}\nseverity: ${severity}\nstatus: open\nfound: 2026-09-13\nlane: agent/seam-audit-0912-b\nfix:\norigin: audit\naffected: 091d6e7f3 source\ninstaller: unverified\nrecovery: unconfirmed\n---\n\n# ${title}\n\n## Symptom\n\n${symptom}\n\n## Repro\n\n${repro}\n\nSee qa/seam-audit-0912/REPORT.md finding ${id} for exact scope and repair criteria.\n\n## Evidence\n\nCode anchor: ${anchor}. Receipt: \`${receipt}\` in qa/seam-audit-0912/probe-results.json or ui-observations.json. Source baseline 091d6e7f3; product files unchanged through fa85f521f. Repro code is qa/seam-audit-0912/probe.cjs and controlled UI fixture server is fault-proxy.cjs. Evidence class and coverage limits are explicit in the report; no installer proof claimed.\n\n## Verdict\n\nOpen audit finding. No product fix or customer recovery is claimed.\n`;
 fs.writeFileSync(file,text);map.push({id,fingerprint:fp,file});
}
fs.writeFileSync('qa/seam-audit-0912/bug-map.json',JSON.stringify(map,null,2)+'\n');
const idx=spawnSync(process.execPath,['scripts/qa/bugs.mjs','--index','--write'],{encoding:'utf8'});
if(idx.status!==0)throw Error(idx.stdout+idx.stderr);
console.log(JSON.stringify(map,null,2));
